name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip/http
        key: ${{ runner.os }}-pip-http-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-http-

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip/wheels
        key: ${{ runner.os }}-pip-wheels-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-wheels-

    - name: Update submodules
      run: |
        git submodule update --init --recursive

    - name: Install
      run: |
        make install

    - name: Lint
      run: |
        make lint

    - name: Test
      env:
        CI: true
      run: |
        make test
